hmcts/am-role-assignment-refresh-batch

charts/am-role-assignment-refresh-batch/values.preview.template.yaml
charts/am-role-assignment-refresh-batch/values.yaml
src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/RoleAssignmentRefreshApplication.java

Updating Sleep time.

---

build.gradle
charts/am-role-assignment-refresh-batch/values.preview.template.yaml
charts/am-role-assignment-refresh-batch/values.yaml
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/RoleAssignmentRefreshApplication.java
src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/config/BatchConfig.java
src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/constants/RefreshConstants.java
src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/oidc/IdamRepository.java
src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/oidc/OIdcAdminConfiguration.java
src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/oidc/SecurityUtils.java
src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/task/DeleteExpiredRecords.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml
src/test/java/uk/gov/hmcts/reform/roleassignmentbatch/oidc/SecurityUtilsTest.java

AM-1365
AM-1365: Enable security tokens in refresh job.
```
[ ] Yes
[x] No
```

AM-1365: Enable security tokens in refresh job.

---

.gitignore
src/integrationTest/java/uk/gov/hmcts/reform/roleassignmentrefresh/BaseTest.java
src/integrationTest/java/uk/gov/hmcts/reform/roleassignmentrefresh/RoleAssignmentRefreshIntegrationTest.java
src/integrationTest/resources/sql/insert_refresh_jobs.sql

https://tools.hmcts.net/jira/browse/AM-1373
Integration tests for refresh batch
[ ] Yes
[x ] No

Integration tests for refresh batch

---

charts/am-role-assignment-refresh-batch/values.yaml

AM-1392
AM-1392: Rollback the change.
```
[ ] Yes
[x] No
```

AM-1392: Rollback the change.

---

Jenkinsfile_nightly

Adding Jenkins Nightly.

---

build.gradle

jar upgrade and fix build failure

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/AM-1430
Add s2s secret
```
[ ] Yes
[X] No
```

Add RAS refresh batch S2S secret

---

infrastructure/terraform.tf

Adding Azure AD in TF file.

---

build.gradle
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/AM-1605

1605 Removing secrets

---

build.gradle
charts/am-role-assignment-refresh-batch/Chart.yaml
charts/am-role-assignment-refresh-batch/values.aat.template.yaml
charts/am-role-assignment-refresh-batch/values.yaml

https://tools.hmcts.net/confluence/display/RSTR/CHG5006041+-+PRD+and+AM+Postgress+Databases+Upgrade+to+v11+Release+Implementation+Plan
```
[ ] Yes
[X] No
```

Update configurations to point to v1 DB

---

Jenkinsfile_CNP
Jenkinsfile_nightly

NA
Enable nightly build and implement fortify scan
```
[ ] Yes
[X] No
```

Enable nightly build and implement fortify

---

build.gradle

- [x ] commit messages are meaningful and follow good commit message guidelines
```
[ ] Yes
[ x] No
```

Removing jcenter

---

Jenkinsfile_nightly

disable fortify temp

---

Jenkinsfile_nightly
build.gradle

ignore fortify scan failures

---

charts/am-role-assignment-refresh-batch/Chart.yaml

Updated the chart version

---

charts/am-role-assignment-refresh-batch/Chart.yaml

Am 2066 java upgrade

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/integrationTest/java/uk/gov/hmcts/reform/roleassignmentrefresh/BaseTest.java

https://tools.hmcts.net/jira/browse/AM-2068
Gradle upgrade to 7.4.1
```
[ ] Yes
[X ] No
```

Gradle upgrade to 7.4.1

---

build.gradle

Updated postgres dependency

---

Dockerfile
build.gradle

https://tools.hmcts.net/jira/browse/AM-2138
Upgrading to `Java 17`
```
[ ] Yes
[x] No
```

AM-2138: Upgrading to Java 17

---

build.gradle

class not found issue
```
[ ] Yes
[ X] No
```

dependency jar

---

build.gradle

https://tools.hmcts.net/jira/browse/AM-2311

CVE Postgres

---

build.gradle

Postgres version
```
[ ] Yes
[X] No
```

update postgres version

---

charts/am-role-assignment-refresh-batch/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2591

Suppress CVE-2021-4277

---

build.gradle

dependency check

---

build.gradle

https://tools.hmcts.net/jira/browse/AM-2654
```
[ ] Yes
[X] No
```

S2s Client version

---

build.gradle
charts/am-role-assignment-refresh-batch/Chart.yaml
config/owasp/suppressions.xml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/AM-2517
```
[ ] Yes
[x] No
```

springboot upgrade 2.7.7

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2668
```
[ ] Yes
[X] No
```

RAS-Refresh:Application Nightly build failed due to CVE-2022-45688

---

build.gradle

https://tools.hmcts.net/jira/browse/AM-2681
```
[ ] Yes
[X] No
```

ORM and Refresh Batch-Application Nightly Build failed

---

build.gradle
charts/am-role-assignment-refresh-batch/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2520
Cleanup suppression / CVEs
```
[ ] Yes
[ x] No
```

Am 2520 cleanup suppressions

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2786
CVE-2023-20873 Fix spring boot upgraded 2.7.11 
https://tools.hmcts.net/jira/browse/AM-2787
CVE-2023-20862 spring security upgraded 5.8.3
```
[ ] Yes
[x] No
```

AM-2786 CVE-2023-20873 AM-2787 CVE-2023-20862

---

charts/am-role-assignment-refresh-batch/Chart.yaml

https://tools.hmcts.net/jira/browse/AM-2806
```
[ ] Yes
[*] No
```

AM-2806: Upgrade chart-job version

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2851
CVE-2023-2976 guava 32.0.1-jre
```
[ ] Yes
[x] No
```

AM-2851 CVE-2023-2976 guava 32.0.1-jre, suppression removed

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2883
CVE-2023-34035 Suppression
```
[ ] Yes
[x] No
```

AM-2883 CVE-2023-34035 Suppression

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2883
CVE-2023-34035 spring-security upgraded 5.8.5
```
[ ] Yes
[x] No
```

AM-2888 CVE-2023-34035 spring-security upgraded 5.8.5

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/AM-2985
Connect to v15 JBS ITHC - Remove 'ithc' from git branchesToSync

AM-2985 Connect to v15 JBS ITHC - Remove 'ithc' from git branchesToSync

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/AM-2943
v15 Migration Resync ITHC Perftest

AM-2943 v15 Migration Resync ITHC Perftest

---

charts/am-role-assignment-refresh-batch/Chart.yaml

https://tools.hmcts.net/jira/browse/AM-3055
Bump Helm Job Chart Version to 1.1.5

AM-3055 Bump Helm Job Chart Version to 1.1.5

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/AM-2839
CVE-2023-35116 Remove Suppression CVE disappeared

AM-2839 CVE-2023-35116 Remove Suppression CVE disappeared

---

charts/am-role-assignment-refresh-batch/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSAM-86
Helm chart upgrade - chart-job version to ~2.1.1

DTSAM-86 Helm chart upgrade - chart-job version to ~2.1.1

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSAM-269
Increase RARB feign timeout to 15 seconds

DTSAM-269 Increase RARB feign timeout to 15 seconds

---

build.gradle

[DTSAM-263](https://tools.hmcts.net/jira/browse/DTSAM-263) _"Updates to allow AM Refreshes to be run unmanned"_
[DTSAM-319](https://tools.hmcts.net/jira/browse/DTSAM-319) _"AM Refresh Updates: Refresh Batch: process"_
Test alternative sonarqube config for #788.

Test alternative sonarqube config for #788

---

build.gradle

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

DTSAM-820 revert the logback version done by renovate PR to 1.2.13

---

config/owasp/suppressions.xml

[DTSAM-976](https://tools.hmcts.net/jira/browse/DTSAM-976) _"Review CVE suppressions after SB3 + DTSPO-23398"_
Adjust CVE suppressions after SB3 + DTSPO-23398

DTSAM-976 Review CVE suppressions after SB3 + DTSPO-23398

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSAM-1008
Renovate review W/C 2025-07-04 Fix RARB

DTSAM-1008 Renovate review W/C 2025-07-04 Fix RARB
